### PR TITLE
Prometheus servicemonitor support

### LINKED ISSUE #152: Add Prometheus service monitor to logging
- [x] service monitor deffiniton (fluentbit, fluentd)
- [x] Headless Service (fluentbit, fluentd)
- [x] Docs

### LINKED ISSUE #167: Expose resource settings for in v1 helm chart
**Describe the bug**
The helm chart for v1 logging-operator-fluent hard-codes empty resource settings. This should be exposed as configurable. See: https://github.com/banzaicloud/logging-operator/blob/v1/charts/logging-operator-fluent/templates/fluentd-cr.yaml#L21

**Steps to reproduce the issue:**
See helm chart.

**Expected behavior**
The helm chart checks for fluentd,resources or some similar variable before expression resource settings.

**Additional context**
This is about v1 of the logger.

### PR DESCRIPTION
**Pull request by ahma**
| Q               | A
| --------------- | ---
| Bug fix?        | no
| New feature?    | yes
| API breaks?     | no
| Deprecations?   | no
| Related tickets | fixes #152  
| License         | Apache 2.0

### What's in this PR?
Prometheus annotation, and servicemonitor support for fluentd and fluentbit services

### Checklist
- [x] Error handling code meets the [guideline](https://github.com/banzaicloud/pipeline/blob/master/docs/error-handling-guide.md)
- [x] Logging code meets the guideline (TODO)
- [x] User guide and development docs updated (if needed)

### To Do
- [x] Documentation

### CODE REVIEW

File: pkg/resources/fluentd/service.go [hunk 1]
```diff
@@ -34,8 +37,58 @@ func (r *Reconciler) service() runtime.Object {
...
+		return &v1.ServiceMonitor{
+			ObjectMeta: templates.FluentdObjectMeta(r.Logging.QualifiedName(ServiceName+"-metrics"), util.MergeLabels(r.Logging.Labels, r.getFluentdLabels(), generataLoggingRefLabels(r.Logging.ObjectMeta.GetName())), r.Logging),
+			Spec: v1.ServiceMonitorSpec{
+				JobLabel:        "",
+				TargetLabels:    nil,
+				PodTargetLabels: nil,
+				Endpoints: []v1.Endpoint{{
+					Port:          "metrics",
+					Path:          r.Logging.Spec.FluentdSpec.Metrics.Path,
+					Interval:      r.Logging.Spec.FluentdSpec.Metrics.Interval,
```
Comment (tarokkk) [inline pkg/resources/fluentd/service.go]: We should have default value for this

File: pkg/resources/fluentd/service.go [hunk 2]
```diff
@@ -34,8 +37,58 @@ func (r *Reconciler) service() runtime.Object {
...
+					ScrapeTimeout: r.Logging.Spec.FluentdSpec.Metrics.Timeout,
```
Comment (tarokkk) [inline pkg/resources/fluentd/service.go]: We should have default value for this
