### PR TITLE
Elastic Output config

### LINKED ISSUE #314: reload_connections setting is not applied to fluentd
Was struggling with an issue related to fluentd freezing after "failed to flush the buffer" warning in fluentd logs, found a solution described here https://github.com/uken/fluent-plugin-elasticsearch/issues/525#issuecomment-475525764 
But the attempt to change reload_connections to false in my ClusterOutput was not applied to fluentd, sample ClusterOutput:
```yaml
apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterOutput
metadata:
  name: cluster-elasticsearch
spec:
  elasticsearch:
    host: logging-cluster-es-http.logging.svc.cluster.local
    port: 9200
    scheme: https
    ssl_verify: false
    ssl_version: TLSv1_2
    reconnect_on_error: true
    reload_on_failure: true
    reload_connections: false
    buffer:
      timekey: 1m
      timekey_wait: 5s
      timekey_use_utc: true
      chunk_limit_size: 16MB
      flush_mode: interval
      flush_interval: 5s
      flush_thread_count: 8
```

### PR DESCRIPTION
**Pull request by ahma**
| Q               | A
| --------------- | ---
| Bug fix?        | yes
| New feature?    | no
| API breaks?     | no
| Deprecations?   | no
| Related tickets | fixes #314 
| License         | Apache 2.0

### Checklist
- [x] Error handling code meets the [guideline](https://github.com/banzaicloud/pipeline/blob/master/docs/error-handling-guide.md)
- [x] Logging code meets the guideline (TODO)
- [x] User guide and development docs updated (if needed)
- [x] Related Helm chart(s) updated (if needed)

### CODE REVIEW

File: pkg/sdk/model/output/elasticsearch.go [hunk 1]
```diff
@@ -118,13 +120,14 @@ type ElasticsearchOutput struct {
 	// You can specify times of retry putting template.(default: 10)
 	MaxRetryPuttingTemplate string `json:"max_retry_putting_template,omitempty"`
 	// Indicates whether to fail when max_retry_putting_template is exceeded. If you have multiple output plugin, you could use this property to do not fail on fluentd statup.(default: true)
-	FailOnPuttingTemplateRetryExceed bool `json:"fail_on_putting_template_retry_exceed,omitempty"`
-
+	// +kubebuilder:validation:Optional
+	FailOnPuttingTemplateRetryExceed *bool `json:"fail_on_putting_template_retry_exceed,omitempty,omitempty" plugin:"default:true"`
```
Comment (pepov) [inline pkg/sdk/model/output/elasticsearch.go]:
```suggestion
	FailOnPuttingTemplateRetryExceed *bool `json:"fail_on_putting_template_retry_exceed,omitempty" plugin:"default:true"`
```

File: pkg/sdk/model/output/elasticsearch.go [hunk 2]
```diff
@@ -118,13 +120,14 @@ type ElasticsearchOutput struct {
...
 	// You can specify times of retry obtaining Elasticsearch version.(default: 15)
 	MaxRetryGetEsVersion string `json:"max_retry_get_es_version,omitempty"`
 	// You can specify HTTP request timeout.(default: 5s)
 	RequestTimeout string `json:"request_timeout,omitempty"`
 	// You can tune how the elasticsearch-transport host reloading feature works.(default: true)
+	// +kubebuilder:validation:Optional
 	ReloadConnections bool `json:"reload_connections,omitempty"`
```
Comment (pepov) [inline pkg/sdk/model/output/elasticsearch.go]:
```suggestion
	ReloadConnections bool `json:"reload_connections,omitempty" plugin:"default:true"`
```
