### PR TITLE
Loki output extract_kubernetes_labels default false fix

### LINKED ISSUE #403: Output - Loki - extract_kubernetes_labels key is ignored
**Describe the bug**:
Setting `extract_kubernetes_labels` key to false is ignored by the operator. Not even a configcheck is generated.

**Expected behaviour**:
The option to be set to false in the fluentd config.

**Steps to reproduce the bug**:
On a Loki output set `extract_kubernetes_labels` to false. Get the fluentd config or the configcheck pod's logs and the key will be true. Logging operator doesn't notice the change if you re-apply the Output with different values for that property.

**Additional context**:
The property is described [here](https://github.com/banzaicloud/logging-operator/blob/3.0.0/docs/plugins/outputs/loki.md#configuration).

**Environment details**:
- Kubernetes version (e.g. v1.15.2): 1.16
- Cloud-provider/provisioner (e.g. AKS, GKE, EKS, PKE etc): on-premise
- logging-operator version (e.g. 2.1.1): 3.0.0
- Install method (e.g. helm or static manifests): helm
- Logs from the misbehaving component (and any other relevant logs):
- Resource definition (possibly in YAML format) that caused the issue, without sensitive data:

/kind bug

### PR DESCRIPTION
**Pull request by ahma**
| Q               | A
| --------------- | ---
| Bug fix?        | yes
| New feature?    | no
| API breaks?     | no
| Deprecations?   | no
| Related tickets | fixes #403
| License         | Apache 2.0

### Checklist

- [x] Error handling code meets the [guideline](https://github.com/banzaicloud/pipeline/blob/master/docs/error-handling-guide.md)
- [x] Logging code meets the guideline (TODO)
- [x] User guide and development docs updated (if needed)
- [x] Related Helm chart(s) updated (if needed)

### CODE REVIEW

File: pkg/sdk/model/output/loki.go [hunk 1]
```diff
@@ -64,7 +64,7 @@ type LokiOutput struct {
 	// Format to use when flattening the record to a log line: json, key_value (default: key_value)
 	LineFormat string `json:"line_format,omitempty" plugin:"default:json"`
 	// Extract kubernetes labels as loki labels (default: false)
-	ExtractKubernetesLabels bool `json:"extract_kubernetes_labels,omitempty"`
+	ExtractKubernetesLabels *bool `json:"extract_kubernetes_labels,omitempty" plugin:"default:false"`
```
Comment (pepov) [inline pkg/sdk/model/output/loki.go]:
```suggestion
	ExtractKubernetesLabels *bool `json:"extract_kubernetes_labels,omitempty"`
```

File: pkg/sdk/model/output/loki.go [hunk 2]
```diff
@@ -125,7 +125,7 @@ func (l *LokiOutput) ToDirective(secretLoader secret.SecretLoader, id string) (t
 		} else {
 			l.RemoveKeys = []string{"kubernetes"}
 		}
-		l.ExtractKubernetesLabels = true
+		l.ExtractKubernetesLabels = util.BoolPointer(true)
```
Comment (pepov) [inline pkg/sdk/model/output/loki.go]:
```suggestion
		if l.ExtractKubernetesLabels == nil {
			l.ExtractKubernetesLabels = util.BoolPointer(true)
		}
```

Comment (ahma) [reply pkg/sdk/model/output/loki.go]: Thanks
