### PR TITLE
Fix configcheck secret to be identical to production config

### LINKED ISSUE #681: Configcheck generated configuration missing the <system> predicates
The missing configuration parts make the config check failing to pass.

### PR DESCRIPTION
**Pull request by tarokkk**
| Q               | A
| --------------- | ---
| Bug fix?        | yes
| New feature?    | no
| API breaks?     | no
| Deprecations?   | no
| Related tickets | fixes #681
| License         | Apache 2.0

### What's in this PR?
Make configcheck identical to production config

### CODE REVIEW

File: pkg/resources/fluentd/configsecret.go [hunk 1]
```diff
@@ -76,16 +76,25 @@ func (r *Reconciler) secretConfig() (runtime.Object, reconciler.DesiredState, er
...
 		ObjectMeta: r.FluentdObjectMeta(SecretConfigName, ComponentFluentd),
-		Data: map[string][]byte{
-			"fluent.conf":  []byte(fluentdDefaultTemplate),
-			"input.conf":   []byte(inputConfig),
-			"devnull.conf": []byte(fluentdOutputTemplate),
-		},
+		Data:       configMap,
 	}
 
 	configs.Data["fluentlog.conf"] = []byte(fmt.Sprintf(fluentLog, r.Logging.Spec.FluentdSpec.FluentLogDestination))
```
Comment (siliconbrain) [inline pkg/resources/fluentd/configsecret.go:100]: I'd move this up, and set the key on `configMap`:
```suggestion
	configMap["fluentlog.conf"] = []byte(fmt.Sprintf(fluentLog, r.Logging.Spec.FluentdSpec.FluentLogDestination))
```

**Review by siliconbrain — APPROVED** [review]
lgtm

File: pkg/resources/fluentd/configsecret.go [hunk 2]
```diff
@@ -76,16 +76,25 @@ func (r *Reconciler) secretConfig() (runtime.Object, reconciler.DesiredState, er
...
+	configs := map[string][]byte{
+		"fluent.conf":  []byte(fluentdDefaultTemplate),
+		"input.conf":   []byte(inputConfig),
+		"devnull.conf": []byte(fluentdOutputTemplate),
 	}
+	return configs, nil
+}
 
+func (r *Reconciler) secretConfig() (runtime.Object, reconciler.DesiredState, error) {
+	configMap, err := r.generateConfigSecret()
```
Comment (bonifaido) [inline pkg/resources/fluentd/configsecret.go:91]: I would call this something else than a configMap.

**Review by bonifaido — APPROVED** [review]

**Review by bshifter — APPROVED** [review]

**Review by pepov — APPROVED** [review]
